import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import pg from 'pg'
import path from 'path'
import { fileURLToPath } from 'url'
import crypto from 'crypto'

const { Pool } = pg
const app = express()
const PORT = Number(process.env.PORT || 10000)
const JWT_SECRET = process.env.JWT_SECRET || 'preview-only-change-me'
const SUPPORT_AGENT_KEY = process.env.SUPPORT_AGENT_KEY || 'bizora-preview-agent'
const ADMIN_KEY = process.env.ADMIN_KEY || SUPPORT_AGENT_KEY
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pool = process.env.DATABASE_URL ? new Pool({ connectionString:process.env.DATABASE_URL, ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false }) : null
const mem = { users:[], merchants:[], requests:[], messages:[], tickets:[], supportMessages:[], verifications:[], payments:[], disputes:[] }

app.use(helmet({contentSecurityPolicy:false}))
app.use(cors({origin:true,credentials:true}))
app.use(express.json({limit:'1mb'}))

const now=()=>new Date().toISOString()
const makeId=p=>`${p}_${crypto.randomUUID().replaceAll('-','').slice(0,18)}`
const slugify=s=>String(s||'business').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45)||'business'
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,createdAt:u.created_at||u.createdAt})
const sign=u=>jwt.sign({sub:u.id,role:u.role},JWT_SECRET,{expiresIn:'7d'})
const clean=s=>String(s||'').trim()
function supportWindow(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Lagos',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const hour=Number(parts.find(p=>p.type==='hour')?.value||0),minute=Number(parts.find(p=>p.type==='minute')?.value||0);return{humanOpen:hour>=8&&hour<20,timezone:'Africa/Lagos',localTime:`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`,opensAt:'08:00',closesAt:'20:00',hoursPerDay:12}}

async function ensureSchema(){if(!pool)return;await pool.query(`
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('customer','merchant')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS merchant_profiles(id TEXT PRIMARY KEY,user_id TEXT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,business_name TEXT NOT NULL,provider_slug TEXT UNIQUE,category TEXT NOT NULL,service_name TEXT,starting_price INTEGER,area TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'unverified',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE merchant_profiles ADD COLUMN IF NOT EXISTS provider_slug TEXT; ALTER TABLE merchant_profiles ADD COLUMN IF NOT EXISTS service_name TEXT; ALTER TABLE merchant_profiles ADD COLUMN IF NOT EXISTS starting_price INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS idx_merchant_provider_slug ON merchant_profiles(provider_slug) WHERE provider_slug IS NOT NULL;
CREATE TABLE IF NOT EXISTS service_requests(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider_slug TEXT NOT NULL,provider_name TEXT NOT NULL,service TEXT NOT NULL,details TEXT NOT NULL,location TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending_quote',quote_amount INTEGER,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,request_id TEXT NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,subject TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ai_active',ai_confidence NUMERIC(4,3),assigned_agent TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS support_messages(id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,sender_type TEXT NOT NULL CHECK(sender_type IN ('customer','ai','agent')),sender_name TEXT NOT NULL,body TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS verification_records(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,method TEXT NOT NULL,status TEXT NOT NULL,reference TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,request_id TEXT NOT NULL,customer_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider_name TEXT NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'NGN',status TEXT NOT NULL DEFAULT 'held',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS disputes(id TEXT PRIMARY KEY,payment_id TEXT NOT NULL,opened_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',resolution TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_requests_customer ON service_requests(customer_id); CREATE INDEX IF NOT EXISTS idx_requests_provider ON service_requests(provider_slug); CREATE INDEX IF NOT EXISTS idx_messages_request ON messages(request_id); CREATE INDEX IF NOT EXISTS idx_support_customer ON support_tickets(customer_id); CREATE INDEX IF NOT EXISTS idx_payments_customer ON payments(customer_id);
`)}

async function findUserByEmail(email){return pool?(await pool.query('SELECT * FROM users WHERE email=$1 LIMIT 1',[email])).rows[0]:mem.users.find(u=>u.email===email)}
async function findUserById(uid){return pool?(await pool.query('SELECT * FROM users WHERE id=$1 LIMIT 1',[uid])).rows[0]:mem.users.find(u=>u.id===uid)}
async function getMerchant(uid){return pool?(await pool.query('SELECT * FROM merchant_profiles WHERE user_id=$1 LIMIT 1',[uid])).rows[0]||null:mem.merchants.find(m=>m.user_id===uid)||null}
async function getMerchantBySlug(slug){return pool?(await pool.query('SELECT * FROM merchant_profiles WHERE provider_slug=$1 LIMIT 1',[slug])).rows[0]||null:mem.merchants.find(m=>m.provider_slug===slug)||null}
async function getRequest(rid){return pool?(await pool.query('SELECT * FROM service_requests WHERE id=$1',[rid])).rows[0]||null:mem.requests.find(r=>r.id===rid)||null}
async function getVerification(uid){return pool?(await pool.query('SELECT * FROM verification_records WHERE user_id=$1',[uid])).rows[0]||null:mem.verifications.find(v=>v.user_id===uid)||null}
async function auth(req,res,next){const t=req.headers.authorization?.startsWith('Bearer ')?req.headers.authorization.slice(7):null;if(!t)return res.status(401).json({error:'Authentication required'});try{const p=jwt.verify(t,JWT_SECRET),u=await findUserById(p.sub);if(!u)return res.status(401).json({error:'Account no longer exists'});req.user=u;next()}catch{return res.status(401).json({error:'Invalid or expired session'})}}
const agentAuth=(req,res,next)=>req.headers['x-support-key']===SUPPORT_AGENT_KEY?next():res.status(401).json({error:'Invalid support staff passcode'})
const adminAuth=(req,res,next)=>req.headers['x-admin-key']===ADMIN_KEY?next():res.status(401).json({error:'Invalid admin passcode'})
async function canAccessRequest(user,request){if(!request)return false;if(user.role==='customer')return request.customer_id===user.id;const m=await getMerchant(user.id);return Boolean(m?.provider_slug&&m.provider_slug===request.provider_slug)}
async function uniqueSlug(name,userId){const base=slugify(name);let candidate=base;let n=1;while(true){const existing=await getMerchantBySlug(candidate);if(!existing||existing.user_id===userId)return candidate;candidate=`${base}-${++n}`}}

app.get('/api/health',(_req,res)=>res.json({ok:true,milestone:100,mode:'inspection',database:pool?'postgres':'preview-memory',marketplace:'merchant-scoped',payments:'sandbox-escrow',verification:'sandbox-safe',support:'ai-human'}))
app.get('/api/support/status',(_req,res)=>res.json(supportWindow()))
app.post('/api/auth/register',async(req,res)=>{try{const name=clean(req.body.name),email=clean(req.body.email).toLowerCase(),password=String(req.body.password||''),role=req.body.role==='merchant'?'merchant':'customer';if(name.length<2||!email.includes('@')||password.length<8)return res.status(400).json({error:'Use a valid name, email and password of at least 8 characters'});if(await findUserByEmail(email))return res.status(409).json({error:'An account with this email already exists'});const u={id:makeId('usr'),name,email,password_hash:await bcrypt.hash(password,12),role,created_at:now()};const user=pool?(await pool.query('INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING *',[u.id,u.name,u.email,u.password_hash,u.role])).rows[0]:(mem.users.push(u),u);res.status(201).json({token:sign(user),user:publicUser(user)})}catch(e){console.error(e);res.status(500).json({error:'Could not create account'})}})
app.post('/api/auth/login',async(req,res)=>{try{const u=await findUserByEmail(clean(req.body.email).toLowerCase());if(!u||!(await bcrypt.compare(String(req.body.password||''),u.password_hash)))return res.status(401).json({error:'Email or password is incorrect'});res.json({token:sign(u),user:publicUser(u)})}catch{res.status(500).json({error:'Could not sign in'})}})
app.get('/api/me',auth,async(req,res)=>res.json({user:publicUser(req.user),merchant:req.user.role==='merchant'?await getMerchant(req.user.id):null,verification:await getVerification(req.user.id)}))

app.put('/api/merchant/profile',auth,async(req,res)=>{if(req.user.role!=='merchant')return res.status(403).json({error:'Merchant account required'});const businessName=clean(req.body.businessName),category=clean(req.body.category),serviceName=clean(req.body.serviceName||req.body.category),area=clean(req.body.area),description=clean(req.body.description),startingPrice=Math.round(Number(req.body.startingPrice||0));if(!businessName||!category||!serviceName||!area||description.length<20||startingPrice<0)return res.status(400).json({error:'Complete all business listing fields'});const existing=await getMerchant(req.user.id),providerSlug=existing?.provider_slug||await uniqueSlug(businessName,req.user.id);if(pool){const row=existing?(await pool.query('UPDATE merchant_profiles SET business_name=$1,category=$2,service_name=$3,starting_price=$4,area=$5,description=$6,provider_slug=$7 WHERE user_id=$8 RETURNING *',[businessName,category,serviceName,startingPrice,area,description,providerSlug,req.user.id])).rows[0]:(await pool.query('INSERT INTO merchant_profiles(id,user_id,business_name,provider_slug,category,service_name,starting_price,area,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[makeId('mer'),req.user.id,businessName,providerSlug,category,serviceName,startingPrice,area,description])).rows[0];return res.json({merchant:row})}if(existing){Object.assign(existing,{business_name:businessName,provider_slug:providerSlug,category,service_name:serviceName,starting_price:startingPrice,area,description});return res.json({merchant:existing})}const row={id:makeId('mer'),user_id:req.user.id,business_name:businessName,provider_slug:providerSlug,category,service_name:serviceName,starting_price:startingPrice,area,description,status:'unverified',created_at:now()};mem.merchants.push(row);res.json({merchant:row})})
app.get('/api/providers',async(_req,res)=>{const rows=pool?(await pool.query("SELECT provider_slug,business_name,category,service_name,starting_price,area,description,status FROM merchant_profiles WHERE status='verified' AND provider_slug IS NOT NULL ORDER BY created_at DESC")).rows:mem.merchants.filter(m=>m.status==='verified'&&m.provider_slug).map(({provider_slug,business_name,category,service_name,starting_price,area,description,status})=>({provider_slug,business_name,category,service_name,starting_price,area,description,status}));res.json({providers:rows})})
app.get('/api/providers/:slug',async(req,res)=>{const p=await getMerchantBySlug(req.params.slug);if(!p||p.status!=='verified')return res.status(404).json({error:'Provider not found'});const{provider_slug,business_name,category,service_name,starting_price,area,description,status}=p;res.json({provider:{provider_slug,business_name,category,service_name,starting_price,area,description,status}})})

app.post('/api/requests',auth,async(req,res)=>{if(req.user.role!=='customer')return res.status(403).json({error:'Customer account required'});const providerSlug=clean(req.body.providerSlug),provider=await getMerchantBySlug(providerSlug);const providerName=provider?.business_name||clean(req.body.providerName);if(provider&&provider.status!=='verified')return res.status(403).json({error:'Provider is not verified'});const r={id:makeId('req'),customer_id:req.user.id,provider_slug:providerSlug,provider_name:providerName,service:clean(req.body.service||provider?.service_name),details:clean(req.body.details),location:clean(req.body.location),status:'pending_quote',quote_amount:null,created_at:now(),updated_at:now()};if(!r.provider_slug||!r.provider_name||!r.service||r.details.length<10||!r.location)return res.status(400).json({error:'Complete the service request details'});if(pool)return res.status(201).json({request:(await pool.query('INSERT INTO service_requests(id,customer_id,provider_slug,provider_name,service,details,location) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[r.id,r.customer_id,r.provider_slug,r.provider_name,r.service,r.details,r.location])).rows[0]});mem.requests.unshift(r);res.status(201).json({request:r})})
app.get('/api/requests',auth,async(req,res)=>{if(req.user.role==='customer'){const rows=pool?(await pool.query('SELECT * FROM service_requests WHERE customer_id=$1 ORDER BY created_at DESC',[req.user.id])).rows:mem.requests.filter(r=>r.customer_id===req.user.id);return res.json({requests:rows})}const m=await getMerchant(req.user.id);if(!m?.provider_slug)return res.json({requests:[]});const rows=pool?(await pool.query('SELECT * FROM service_requests WHERE provider_slug=$1 ORDER BY created_at DESC',[m.provider_slug])).rows:mem.requests.filter(r=>r.provider_slug===m.provider_slug);res.json({requests:rows})})
app.get('/api/requests/:requestId',auth,async(req,res)=>{const r=await getRequest(req.params.requestId);if(!r)return res.status(404).json({error:'Request not found'});if(!(await canAccessRequest(req.user,r)))return res.status(403).json({error:'Not your request'});res.json({request:r})})
app.patch('/api/requests/:requestId',auth,async(req,res)=>{const r=await getRequest(req.params.requestId);if(!r)return res.status(404).json({error:'Request not found'});if(!(await canAccessRequest(req.user,r)))return res.status(403).json({error:'Not your request'});const status=clean(req.body.status),customerAllowed=['accepted','completed','cancelled'],merchantAllowed=['quoted','in_progress','completed','cancelled'];if(!(req.user.role==='customer'?customerAllowed:merchantAllowed).includes(status))return res.status(400).json({error:'That status change is not allowed for this account'});const quote=req.user.role==='merchant'&&req.body.quoteAmount!=null?Math.round(Number(req.body.quoteAmount)):null;if(status==='quoted'&&(!Number.isFinite(quote)||quote<100))return res.status(400).json({error:'Enter a quote of at least ₦100'});if(pool)return res.json({request:(await pool.query('UPDATE service_requests SET status=$1,quote_amount=COALESCE($2,quote_amount),updated_at=NOW() WHERE id=$3 RETURNING *',[status,quote,r.id])).rows[0]});r.status=status;if(quote!=null)r.quote_amount=quote;r.updated_at=now();res.json({request:r})})
app.get('/api/requests/:requestId/messages',auth,async(req,res)=>{const r=await getRequest(req.params.requestId);if(!r)return res.status(404).json({error:'Request not found'});if(!(await canAccessRequest(req.user,r)))return res.status(403).json({error:'Not your request'});const rows=pool?(await pool.query('SELECT m.*,u.name AS sender_name FROM messages m JOIN users u ON u.id=m.sender_id WHERE request_id=$1 ORDER BY m.created_at ASC',[r.id])).rows:mem.messages.filter(m=>m.request_id===r.id);res.json({request:r,messages:rows})})
app.post('/api/requests/:requestId/messages',auth,async(req,res)=>{const r=await getRequest(req.params.requestId);if(!r)return res.status(404).json({error:'Request not found'});if(!(await canAccessRequest(req.user,r)))return res.status(403).json({error:'Not your request'});const body=clean(req.body.body);if(!body||body.length>1500)return res.status(400).json({error:'Message must be 1–1500 characters'});const m={id:makeId('msg'),request_id:r.id,sender_id:req.user.id,sender_name:req.user.name,body,created_at:now()};if(pool){const row=(await pool.query('INSERT INTO messages(id,request_id,sender_id,body) VALUES($1,$2,$3,$4) RETURNING *',[m.id,m.request_id,m.sender_id,m.body])).rows[0];return res.status(201).json({message:{...row,sender_name:req.user.name}})}mem.messages.push(m);res.status(201).json({message:m})})
app.get('/api/merchant/stats',auth,async(req,res)=>{if(req.user.role!=='merchant')return res.status(403).json({error:'Merchant account required'});const m=await getMerchant(req.user.id);const requests=!m?.provider_slug?[]:(pool?(await pool.query('SELECT * FROM service_requests WHERE provider_slug=$1 ORDER BY created_at DESC',[m.provider_slug])).rows:mem.requests.filter(r=>r.provider_slug===m.provider_slug));const completed=requests.filter(r=>r.status==='completed');const payments=pool?(await pool.query('SELECT p.* FROM payments p JOIN service_requests r ON r.id=p.request_id WHERE r.provider_slug=$1 ORDER BY p.created_at DESC',[m?.provider_slug||'__none__'])).rows:mem.payments.filter(p=>requests.some(r=>r.id===p.request_id));res.json({stats:{newRequests:requests.filter(r=>r.status==='pending_quote').length,activeJobs:requests.filter(r=>['accepted','in_progress'].includes(r.status)).length,completed:completed.length,quotedValue:requests.reduce((s,r)=>s+(Number(r.quote_amount)||0),0),heldValue:payments.filter(p=>p.status==='held').reduce((s,p)=>s+Number(p.amount||0),0),releasedValue:payments.filter(p=>p.status==='released').reduce((s,p)=>s+Number(p.amount||0),0)},requests:requests.slice(0,30)})})

async function saveVerification(user,method){const v={user_id:user.id,method,status:'verified',reference:makeId('kyc'),updated_at:now()};if(pool)return(await pool.query("INSERT INTO verification_records(user_id,method,status,reference) VALUES($1,$2,'verified',$3) ON CONFLICT(user_id) DO UPDATE SET method=EXCLUDED.method,status='verified',reference=EXCLUDED.reference,updated_at=NOW() RETURNING *",[user.id,method,v.reference])).rows[0];const x=mem.verifications.find(x=>x.user_id===user.id);if(x){Object.assign(x,v);return x}mem.verifications.push(v);return v}
app.get('/api/verification',auth,async(req,res)=>res.json({verification:await getVerification(req.user.id),mode:'sandbox-safe',collectsRealIdentity:false}))
app.post('/api/verification/sandbox-complete',auth,async(req,res)=>{const method=req.user.role==='merchant'?'BUSINESS_SANDBOX':(req.body.method==='BVN'?'BVN_SANDBOX':'NIN_SANDBOX'),v=await saveVerification(req.user,method);if(req.user.role==='merchant'){if(!(await getMerchant(req.user.id)))return res.status(409).json({error:'Create your business profile before verification'});if(pool)await pool.query("UPDATE merchant_profiles SET status='verified' WHERE user_id=$1",[req.user.id]);else{const m=mem.merchants.find(m=>m.user_id===req.user.id);m.status='verified'}}res.json({verification:v,warning:'Inspection-only verification. No real NIN, BVN or government database was queried.'})})

app.get('/api/payments',auth,async(req,res)=>{let rows;if(req.user.role==='customer')rows=pool?(await pool.query('SELECT * FROM payments WHERE customer_id=$1 ORDER BY created_at DESC',[req.user.id])).rows:mem.payments.filter(p=>p.customer_id===req.user.id);else{const m=await getMerchant(req.user.id);rows=!m?.provider_slug?[]:(pool?(await pool.query('SELECT p.* FROM payments p JOIN service_requests r ON r.id=p.request_id WHERE r.provider_slug=$1 ORDER BY p.created_at DESC',[m.provider_slug])).rows:mem.payments.filter(p=>mem.requests.some(r=>r.id===p.request_id&&r.provider_slug===m.provider_slug)))}res.json({payments:rows,mode:'sandbox-escrow'})})
app.post('/api/payments',auth,async(req,res)=>{if(req.user.role!=='customer')return res.status(403).json({error:'Customer account required'});if(!(await getVerification(req.user.id)))return res.status(403).json({error:'verification_required'});const r=await getRequest(clean(req.body.requestId));if(!r||r.customer_id!==req.user.id)return res.status(404).json({error:'Service request not found'});if(!['quoted','accepted','in_progress','completed'].includes(r.status))return res.status(409).json({error:'Wait for a provider quote before payment'});const amount=Math.round(Number(req.body.amount||r.quote_amount||0));if(!Number.isFinite(amount)||amount<100||amount>5000000)return res.status(400).json({error:'Use a sandbox amount between ₦100 and ₦5,000,000'});const existing=pool?(await pool.query("SELECT * FROM payments WHERE request_id=$1 AND status IN ('held','released') LIMIT 1",[r.id])).rows[0]:mem.payments.find(p=>p.request_id===r.id&&['held','released'].includes(p.status));if(existing)return res.status(409).json({error:'A payment already exists for this request'});const p={id:makeId('pay'),request_id:r.id,customer_id:req.user.id,provider_name:r.provider_name,amount,currency:'NGN',status:'held',created_at:now(),updated_at:now()};if(pool)return res.status(201).json({payment:(await pool.query('INSERT INTO payments(id,request_id,customer_id,provider_name,amount,currency,status) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[p.id,p.request_id,p.customer_id,p.provider_name,p.amount,p.currency,p.status])).rows[0],warning:'Sandbox escrow only. No card or bank account was charged.'});mem.payments.unshift(p);res.status(201).json({payment:p,warning:'Sandbox escrow only. No card or bank account was charged.'})})
app.post('/api/payments/:paymentId/release',auth,async(req,res)=>{const p=pool?(await pool.query('SELECT * FROM payments WHERE id=$1',[req.params.paymentId])).rows[0]:mem.payments.find(p=>p.id===req.params.paymentId);if(!p)return res.status(404).json({error:'Payment not found'});if(req.user.role!=='customer'||p.customer_id!==req.user.id)return res.status(403).json({error:'Only the paying customer can release this payment'});if(p.status!=='held')return res.status(409).json({error:'Only held sandbox payments can be released'});if(pool)return res.json({payment:(await pool.query("UPDATE payments SET status='released',updated_at=NOW() WHERE id=$1 RETURNING *",[p.id])).rows[0]});p.status='released';p.updated_at=now();res.json({payment:p})})
app.get('/api/disputes',auth,async(req,res)=>{let rows;if(req.user.role==='customer')rows=pool?(await pool.query('SELECT d.*,p.provider_name,p.amount,p.currency FROM disputes d JOIN payments p ON p.id=d.payment_id WHERE d.opened_by=$1 ORDER BY d.created_at DESC',[req.user.id])).rows:mem.disputes.filter(d=>d.opened_by===req.user.id).map(d=>({...d,...(()=>{const p=mem.payments.find(p=>p.id===d.payment_id);return{provider_name:p?.provider_name,amount:p?.amount,currency:p?.currency}})()}));else rows=[];res.json({disputes:rows})})
app.post('/api/disputes',auth,async(req,res)=>{if(req.user.role!=='customer')return res.status(403).json({error:'Customer account required'});const p=pool?(await pool.query('SELECT * FROM payments WHERE id=$1',[clean(req.body.paymentId)])).rows[0]:mem.payments.find(p=>p.id===req.body.paymentId);if(!p||p.customer_id!==req.user.id)return res.status(404).json({error:'Payment not found'});const reason=clean(req.body.reason);if(reason.length<10||reason.length>1200)return res.status(400).json({error:'Describe the issue in 10–1200 characters'});const d={id:makeId('dsp'),payment_id:p.id,opened_by:req.user.id,reason,status:'open',resolution:null,created_at:now(),updated_at:now()};if(pool)return res.status(201).json({dispute:(await pool.query('INSERT INTO disputes(id,payment_id,opened_by,reason,status) VALUES($1,$2,$3,$4,$5) RETURNING *',[d.id,d.payment_id,d.opened_by,d.reason,d.status])).rows[0]});mem.disputes.unshift(d);res.status(201).json({dispute:d})})

async function latestRequest(uid){return pool?(await pool.query('SELECT * FROM service_requests WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 1',[uid])).rows[0]||null:mem.requests.filter(r=>r.customer_id===uid).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||null}
function aiAnswer(text,r){const q=text.toLowerCase();if(/human|person|agent|representative|customer care/.test(q))return{confidence:0,escalate:true,reply:'I’ll hand this conversation to a human support agent. You will not need to repeat yourself.'};if(/track|status|order|request|job/.test(q))return r?{confidence:.96,escalate:false,reply:`Your latest request is “${r.service}” with ${r.provider_name}. Status: ${String(r.status).replaceAll('_',' ')}.`}:{confidence:.88,escalate:false,reply:'I cannot see a service request on this account yet.'};if(/payment|pay|escrow|refund|money/.test(q))return{confidence:.94,escalate:false,reply:'This inspection build supports sandbox escrow, release and disputes. No real money moves until licensed payment rails are connected.'};if(/verify|nin|bvn|identity/.test(q))return{confidence:.94,escalate:false,reply:'Verification is simulated safely for inspection. Do not send real NIN or BVN data through chat.'};if(/scam|fraud|unsafe|complain|dispute|problem/.test(q))return{confidence:.5,escalate:true,reply:'This needs human review. I am escalating the case with this conversation attached.'};if(/hello|hi|hey/.test(q))return{confidence:.98,escalate:false,reply:'Hi. I’m Bizora Support AI. I can help with requests, accounts, payments, verification and support handoffs.'};return{confidence:.28,escalate:true,reply:'I am not confident enough to answer that reliably, so I am escalating instead of guessing.'}}
async function supportMsg(ticketId,type,name,body){const m={id:makeId('supmsg'),ticket_id:ticketId,sender_type:type,sender_name:name,body,created_at:now()};if(pool)return(await pool.query('INSERT INTO support_messages(id,ticket_id,sender_type,sender_name,body) VALUES($1,$2,$3,$4,$5) RETURNING *',[m.id,ticketId,type,name,body])).rows[0];mem.supportMessages.push(m);return m}
async function ticketById(tid){if(pool)return(await pool.query('SELECT t.*,u.name customer_name,u.email customer_email FROM support_tickets t JOIN users u ON u.id=t.customer_id WHERE t.id=$1',[tid])).rows[0]||null;const t=mem.tickets.find(t=>t.id===tid),u=t&&mem.users.find(u=>u.id===t.customer_id);return t?{...t,customer_name:u?.name,customer_email:u?.email}:null}
async function ticketMessages(tid){return pool?(await pool.query('SELECT * FROM support_messages WHERE ticket_id=$1 ORDER BY created_at',[tid])).rows:mem.supportMessages.filter(m=>m.ticket_id===tid).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at))}
async function updateTicket(tid,patch){if(pool){const t=await ticketById(tid);return(await pool.query('UPDATE support_tickets SET status=$1,ai_confidence=$2,assigned_agent=$3,updated_at=NOW() WHERE id=$4 RETURNING *',[patch.status??t.status,patch.ai_confidence??t.ai_confidence,patch.assigned_agent??t.assigned_agent,tid])).rows[0]}const t=mem.tickets.find(t=>t.id===tid);Object.assign(t,patch,{updated_at:now()});return t}
async function createTicket(user,message){const ans=aiAnswer(message,await latestRequest(user.id)),w=supportWindow(),status=ans.escalate?(w.humanOpen?'waiting_human':'queued_off_hours'):'ai_active',t={id:makeId('sup'),customer_id:user.id,subject:message.slice(0,72),status,ai_confidence:ans.confidence,assigned_agent:null,created_at:now(),updated_at:now()};if(pool)await pool.query('INSERT INTO support_tickets(id,customer_id,subject,status,ai_confidence) VALUES($1,$2,$3,$4,$5)',[t.id,t.customer_id,t.subject,t.status,t.ai_confidence]);else mem.tickets.unshift(t);await supportMsg(t.id,'customer',user.name,message);await supportMsg(t.id,'ai','Bizora Support AI',ans.reply+(ans.escalate?(w.humanOpen?' A human agent is available now.':' Your case is queued for 08:00 WAT.') : ''));return ticketById(t.id)}
app.get('/api/support/tickets',auth,async(req,res)=>{const rows=pool?(await pool.query('SELECT * FROM support_tickets WHERE customer_id=$1 ORDER BY updated_at DESC',[req.user.id])).rows:mem.tickets.filter(t=>t.customer_id===req.user.id);res.json({tickets:rows})})
app.post('/api/support/tickets',auth,async(req,res)=>{const message=clean(req.body.message);if(message.length<2||message.length>2000)return res.status(400).json({error:'Write a support message between 2 and 2000 characters'});const t=await createTicket(req.user,message);res.status(201).json({ticket:t,messages:await ticketMessages(t.id),support:supportWindow()})})
app.get('/api/support/tickets/:ticketId',auth,async(req,res)=>{const t=await ticketById(req.params.ticketId);if(!t||t.customer_id!==req.user.id)return res.status(404).json({error:'Support case not found'});res.json({ticket:t,messages:await ticketMessages(t.id),support:supportWindow()})})
app.post('/api/support/tickets/:ticketId/messages',auth,async(req,res)=>{const t=await ticketById(req.params.ticketId);if(!t||t.customer_id!==req.user.id)return res.status(404).json({error:'Support case not found'});const message=clean(req.body.message);if(!message||message.length>2000)return res.status(400).json({error:'Message must be 1–2000 characters'});await supportMsg(t.id,'customer',req.user.name,message);if(!['waiting_human','queued_off_hours','human_active'].includes(t.status)){const ans=aiAnswer(message,await latestRequest(req.user.id)),w=supportWindow(),status=ans.escalate?(w.humanOpen?'waiting_human':'queued_off_hours'):'ai_active';await updateTicket(t.id,{status,ai_confidence:ans.confidence});await supportMsg(t.id,'ai','Bizora Support AI',ans.reply+(ans.escalate?(w.humanOpen?' Your case is waiting for a human agent.':' Your case is queued for 08:00 WAT.') : ''))}res.json({ticket:await ticketById(t.id),messages:await ticketMessages(t.id),support:supportWindow()})})
app.post('/api/support/tickets/:ticketId/escalate',auth,async(req,res)=>{const t=await ticketById(req.params.ticketId);if(!t||t.customer_id!==req.user.id)return res.status(404).json({error:'Support case not found'});const w=supportWindow(),status=w.humanOpen?'waiting_human':'queued_off_hours';await updateTicket(t.id,{status});await supportMsg(t.id,'ai','Bizora Support AI',w.humanOpen?'I moved this case to the human-support queue.':'Human support is closed. I saved your case for 08:00 WAT.');res.json({ticket:await ticketById(t.id),messages:await ticketMessages(t.id),support:w})})
app.get('/api/support/agent/queue',agentAuth,async(_req,res)=>{const rows=pool?(await pool.query("SELECT t.*,u.name customer_name,u.email customer_email FROM support_tickets t JOIN users u ON u.id=t.customer_id WHERE t.status IN ('waiting_human','queued_off_hours','human_active') ORDER BY t.updated_at")).rows:mem.tickets.filter(t=>['waiting_human','queued_off_hours','human_active'].includes(t.status)).map(t=>{const u=mem.users.find(u=>u.id===t.customer_id);return{...t,customer_name:u?.name,customer_email:u?.email}});res.json({tickets:rows,support:supportWindow()})})
app.get('/api/support/agent/tickets/:ticketId',agentAuth,async(req,res)=>{const t=await ticketById(req.params.ticketId);if(!t)return res.status(404).json({error:'Support case not found'});res.json({ticket:t,messages:await ticketMessages(t.id),support:supportWindow()})})
app.post('/api/support/agent/tickets/:ticketId/reply',agentAuth,async(req,res)=>{const t=await ticketById(req.params.ticketId);if(!t)return res.status(404).json({error:'Support case not found'});if(!supportWindow().humanOpen)return res.status(409).json({error:'Human-agent replies are only enabled 08:00–20:00 WAT'});const message=clean(req.body.message),agentName=clean(req.body.agentName||'Bizora Human Support').slice(0,80);if(!message||message.length>2000)return res.status(400).json({error:'Message must be 1–2000 characters'});await supportMsg(t.id,'agent',agentName,message);await updateTicket(t.id,{status:'human_active',assigned_agent:agentName});res.json({ticket:await ticketById(t.id),messages:await ticketMessages(t.id)})})
app.post('/api/support/agent/tickets/:ticketId/resolve',agentAuth,async(req,res)=>{const t=await ticketById(req.params.ticketId);if(!t)return res.status(404).json({error:'Support case not found'});await updateTicket(t.id,{status:'resolved'});res.json({ticket:await ticketById(t.id)})})

app.get('/api/admin/overview',adminAuth,async(_req,res)=>{const users=pool?Number((await pool.query('SELECT COUNT(*)::int c FROM users')).rows[0].c):mem.users.length,requests=pool?Number((await pool.query('SELECT COUNT(*)::int c FROM service_requests')).rows[0].c):mem.requests.length,payments=pool?(await pool.query('SELECT * FROM payments ORDER BY created_at DESC LIMIT 100')).rows:mem.payments,disputes=pool?(await pool.query('SELECT * FROM disputes ORDER BY created_at DESC LIMIT 100')).rows:mem.disputes,verifications=pool?(await pool.query('SELECT * FROM verification_records ORDER BY updated_at DESC LIMIT 100')).rows:mem.verifications;res.json({overview:{users,requests,heldValue:payments.filter(p=>p.status==='held').reduce((s,p)=>s+Number(p.amount||0),0),releasedValue:payments.filter(p=>p.status==='released').reduce((s,p)=>s+Number(p.amount||0),0),openDisputes:disputes.filter(d=>d.status==='open').length},payments,disputes,verifications})})
app.post('/api/admin/disputes/:id/resolve',adminAuth,async(req,res)=>{const action=['refund','release','dismiss'].includes(req.body.action)?req.body.action:null;if(!action)return res.status(400).json({error:'Choose refund, release or dismiss'});const d=pool?(await pool.query('SELECT * FROM disputes WHERE id=$1',[req.params.id])).rows[0]:mem.disputes.find(d=>d.id===req.params.id);if(!d)return res.status(404).json({error:'Dispute not found'});if(pool){if(action==='refund')await pool.query("UPDATE payments SET status='refunded',updated_at=NOW() WHERE id=$1",[d.payment_id]);if(action==='release')await pool.query("UPDATE payments SET status='released',updated_at=NOW() WHERE id=$1",[d.payment_id]);return res.json({dispute:(await pool.query("UPDATE disputes SET status='resolved',resolution=$1,updated_at=NOW() WHERE id=$2 RETURNING *",[action,d.id])).rows[0]})}const p=mem.payments.find(p=>p.id===d.payment_id);if(p&&action!=='dismiss')p.status=action==='refund'?'refunded':'released';d.status='resolved';d.resolution=action;d.updated_at=now();res.json({dispute:d})})

app.use(express.static(path.join(__dirname,'dist')))
app.get('*',(_req,res)=>res.sendFile(path.join(__dirname,'dist','index.html')))
ensureSchema().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Bizora Commerce V1 inspection listening on ${PORT} (${pool?'postgres':'preview-memory'})`))).catch(e=>{console.error('Startup failed',e);process.exit(1)})
