import React, { useEffect, useMemo, useState } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, MapPin, Search, ShieldCheck, Star } from 'lucide-react'
import { api } from './api.js'
import { useAuth } from './AuthContext.jsx'
import './final.css'

const demo=[
 {slug:'demo-abdul-tech',business_name:'Abdul Tech Repairs',category:'Phone & Computer Repair',service_name:'Phone & laptop repair',starting_price:5000,area:'Barnawa, Kaduna',description:'Fast diagnostics, screen replacement and laptop servicing. Demo provider for inspection.',demo:true,rating:4.9},
 {slug:'demo-zainab-beauty',business_name:'Zainab Beauty Studio',category:'Beauty & Personal Care',service_name:'Beauty appointment',starting_price:7000,area:'Malali, Kaduna',description:'Braids, makeup and event preparation. Demo provider for inspection.',demo:true,rating:4.8},
 {slug:'demo-northern-home',business_name:'Northern Home Care',category:'Home Services',service_name:'Home cleaning',starting_price:8000,area:'Unguwan Rimi, Kaduna',description:'Cleaning and home-maintenance services. Demo provider for inspection.',demo:true,rating:4.7},
]
const money=n=>`₦${Number(n||0).toLocaleString()}`
function Header({back='/'}){return <header className="final-header"><div className="final-shell final-header-inner"><Link className="final-back" to={back}><ArrowLeft size={18}/></Link><Link className="final-brand" to="/"><span>B</span><b>Bizora Commerce</b></Link></div></header>}

export function MarketplaceV1(){
 const[remote,setRemote]=useState([]),[q,setQ]=useState(''),[cat,setCat]=useState('All'),[loading,setLoading]=useState(true)
 useEffect(()=>{api('/api/providers').then(d=>setRemote((d.providers||[]).map(p=>({...p,slug:p.provider_slug,rating:null,demo:false})))).catch(()=>{}).finally(()=>setLoading(false))},[])
 const all=useMemo(()=>[...remote,...demo],[remote]);const cats=useMemo(()=>['All',...new Set(all.map(p=>p.category))],[all]);const rows=useMemo(()=>all.filter(p=>(cat==='All'||p.category===cat)&&`${p.business_name} ${p.category} ${p.service_name} ${p.area}`.toLowerCase().includes(q.toLowerCase())),[all,cat,q])
 return <main className="final-page"><Header/><section className="final-shell final-intro"><div><span className="final-kicker">SERVICES MARKETPLACE</span><h1>Find a verified provider.</h1><p>Merchant-created listings become visible after the safe inspection verification step.</p></div></section><div className="final-shell"><div className="market-v1-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search services, business or area"/></div><div className="market-v1-chips">{cats.map(c=><button className={cat===c?'active':''} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div>{loading?<p className="final-empty">Loading providers…</p>:<div className="market-v1-grid">{rows.map(p=><Link className="market-v1-card" to={`/provider/${p.slug}`} key={p.slug}><div className="provider-v1-top"><span className="provider-v1-avatar">{p.business_name.slice(0,2).toUpperCase()}</span><span className={p.demo?'provider-v1-demo':'provider-v1-verified'}>{p.demo?'Demo':'Verified'}</span></div><h2>{p.business_name}</h2><p>{p.description}</p><div className="provider-v1-meta"><span><BriefcaseBusiness size={14}/>{p.category}</span><span><MapPin size={14}/>{p.area}</span>{p.rating&&<span><Star size={14}/>{p.rating}</span>}</div><div className="provider-v1-bottom"><span>From <b>{money(p.starting_price)}</b></span><span>View <ArrowRight size={15}/></span></div></Link>)}</div>}</div></main>
}

export function ProviderV1(){
 const loc=useLocation(),slug=loc.pathname.split('/').filter(Boolean).pop();const{user,token}=useAuth();const nav=useNavigate();const[p,setP]=useState(()=>demo.find(x=>x.slug===slug)||null);const[loading,setLoading]=useState(!p);const[details,setDetails]=useState('');const[location,setLocation]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false)
 useEffect(()=>{if(p)return;api(`/api/providers/${encodeURIComponent(slug)}`).then(d=>setP({...d.provider,slug:d.provider.provider_slug,demo:false})).catch(e=>setMsg(e.message)).finally(()=>setLoading(false))},[slug])
 async function request(e){e.preventDefault();if(!user){nav('/auth');return}if(user.role!=='customer'){setMsg('Use a Customer account to request a service.');return}setBusy(true);setMsg('');try{const d=await api('/api/requests',{method:'POST',body:JSON.stringify({providerSlug:p.slug,providerName:p.business_name,service:p.service_name,details,location})},token);nav(`/request/${d.request.id}`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 if(loading)return <div className="final-loading">Loading provider…</div>;if(!p)return <main className="final-page"><Header back="/marketplace"/><div className="final-shell final-panel"><h2>Provider unavailable</h2><p>{msg||'This listing could not be found.'}</p></div></main>
 return <main className="final-page"><Header back="/marketplace"/><section className="final-shell provider-v1-hero"><div className="provider-v1-big-avatar">{p.business_name.slice(0,2).toUpperCase()}</div><div><span className="final-kicker">{p.demo?'DEMO PROVIDER':'VERIFIED MERCHANT'}</span><h1>{p.business_name}</h1><p>{p.description}</p><div className="provider-v1-meta"><span><BadgeCheck size={15}/>{p.demo?'Inspection demo':'Verified listing'}</span><span><MapPin size={15}/>{p.area}</span><span><BriefcaseBusiness size={15}/>{p.category}</span></div></div></section><div className="final-shell provider-v1-layout"><section className="final-panel"><h2>{p.service_name}</h2><p>Starting from <b>{money(p.starting_price)}</b>. Final price is agreed through the quote workflow before sandbox escrow can be created.</p><div className="final-warning"><ShieldCheck/><span>Keep requests, messages and inspection payments inside Bizora.</span></div></section><form className="final-panel payment-create" onSubmit={request}><h2>Request this service</h2><label>What do you need?<textarea minLength="10" required value={details} onChange={e=>setDetails(e.target.value)} placeholder="Describe the job clearly…"/></label><label>Location<input required value={location} onChange={e=>setLocation(e.target.value)} placeholder="Your area, Kaduna"/></label><button className="final-primary" disabled={busy}>{busy?'Sending…':'Send request'}</button>{msg&&<div className="final-note">{msg}</div>}</form></div></main>
}

export function MerchantProfileV1(){
 const{user,token,merchant,loading,refresh}=useAuth();const[form,setForm]=useState({businessName:'',category:'Phone & Computer Repair',serviceName:'',startingPrice:'',area:'',description:''});const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false)
 useEffect(()=>{if(merchant)setForm({businessName:merchant.business_name||'',category:merchant.category||'Phone & Computer Repair',serviceName:merchant.service_name||'',startingPrice:String(merchant.starting_price||''),area:merchant.area||'',description:merchant.description||''})},[merchant])
 if(loading)return <div className="final-loading">Loading…</div>;if(!user)return <Navigate to="/auth" replace/>;if(user.role!=='merchant')return <Navigate to="/account" replace/>
 async function save(e){e.preventDefault();setBusy(true);setMsg('');try{const d=await api('/api/merchant/profile',{method:'PUT',body:JSON.stringify({...form,startingPrice:Number(form.startingPrice||0)})},token);await refresh();setMsg(`Saved. Listing ID: ${d.merchant.provider_slug}. Complete verification to make it visible to customers.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="final-page"><Header back="/dashboard"/><section className="final-shell final-intro"><div><span className="final-kicker">MERCHANT LISTING</span><h1>Build your customer-facing profile.</h1><p>Your provider slug stays attached to your merchant account, so only your business receives requests for this listing.</p></div></section><div className="final-shell"><form className="final-panel payment-create" onSubmit={save}><div className="merchant-form-grid"><label>Business name<input required value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Phone & Computer Repair</option><option>Beauty & Personal Care</option><option>Home Services</option><option>Tech & Digital</option><option>Education & Tutoring</option><option>Professional Services</option></select></label><label>Primary service<input required value={form.serviceName} onChange={e=>setForm({...form,serviceName:e.target.value})} placeholder="e.g. Phone screen replacement"/></label><label>Starting price (NGN)<input required inputMode="numeric" value={form.startingPrice} onChange={e=>setForm({...form,startingPrice:e.target.value.replace(/[^0-9]/g,'')})}/></label><label>Area<input required value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="Barnawa, Kaduna"/></label></div><label>Description<textarea minLength="20" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What do you do and why should customers trust you?"/></label><button className="final-primary" disabled={busy}>{busy?'Saving…':'Save business listing'}</button>{msg&&<div className="final-note">{msg}</div>}</form>{merchant&&<div className="final-warning"><ShieldCheck/><span>Status: <b>{merchant.status}</b>. {merchant.status==='verified'?'Your listing is eligible to appear in the marketplace.':'Complete Business verification next.'}</span><Link to="/verify">Verification</Link></div>}</div></main>
}
