import React, { useEffect, useState } from 'react'
import { Link, Navigate, useLocation } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, MessageCircle, Send } from 'lucide-react'
import { api } from './api.js'
import { useAuth } from './AuthContext.jsx'
import './final.css'
const money=n=>`₦${Number(n||0).toLocaleString()}`
const pretty=s=>String(s||'').replaceAll('_',' ')
export default function RequestV1(){
 const{user,token,loading}=useAuth();const loc=useLocation();const id=loc.pathname.split('/').filter(Boolean).pop();const[request,setRequest]=useState(null);const[messages,setMessages]=useState([]);const[text,setText]=useState('');const[quote,setQuote]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false)
 async function load(){try{const d=await api(`/api/requests/${id}/messages`,{},token);setRequest(d.request);setMessages(d.messages||[]);if(d.request?.quote_amount)setQuote(String(d.request.quote_amount));setMsg('')}catch(e){setMsg(e.message)}}
 useEffect(()=>{if(token)load()},[token,id])
 if(loading)return <div className="final-loading">Loading…</div>;if(!user)return <Navigate to="/auth" replace/>
 async function send(e){e.preventDefault();if(!text.trim())return;setBusy(true);try{await api(`/api/requests/${id}/messages`,{method:'POST',body:JSON.stringify({body:text})},token);setText('');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function change(status){setBusy(true);setMsg('');try{const body={status};if(status==='quoted')body.quoteAmount=Number(quote);const d=await api(`/api/requests/${id}`,{method:'PATCH',body:JSON.stringify(body)},token);setRequest(d.request);await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 if(!request&&msg)return <main className="final-page"><header className="final-header"><div className="final-shell final-header-inner"><Link className="final-back" to={user.role==='merchant'?'/dashboard':'/account'}><ArrowLeft size={18}/></Link><Link className="final-brand" to="/"><span>B</span><b>Bizora Commerce</b></Link></div></header><div className="final-shell final-panel"><h2>Request unavailable</h2><p>{msg}</p></div></main>
 if(!request)return <div className="final-loading">Loading request…</div>
 const merchant=user.role==='merchant';return <main className="final-page"><header className="final-header"><div className="final-shell final-header-inner"><Link className="final-back" to={merchant?'/dashboard':'/account'}><ArrowLeft size={18}/></Link><Link className="final-brand" to="/"><span>B</span><b>Bizora Commerce</b></Link></div></header><section className="final-shell final-intro"><div><span className="final-kicker">SERVICE REQUEST</span><h1>{request.service}</h1><p>{request.provider_name} • {request.location}</p></div><span className="final-status">{pretty(request.status)}</span></section><div className="final-shell request-work-grid"><section className="final-panel"><h2>Job details</h2><p>{request.details}</p><div className="request-facts"><span>Provider <b>{request.provider_name}</b></span><span>Current status <b>{pretty(request.status)}</b></span><span>Quote <b>{request.quote_amount?money(request.quote_amount):'Not quoted yet'}</b></span></div>{merchant&&<div className="request-controls"><label>Quote amount (NGN)<input inputMode="numeric" value={quote} onChange={e=>setQuote(e.target.value.replace(/[^0-9]/g,''))} placeholder="15000"/></label><button disabled={busy||!quote} onClick={()=>change('quoted')}>Send quote</button>{['accepted','quoted'].includes(request.status)&&<button disabled={busy} onClick={()=>change('in_progress')}>Start job</button>}{request.status==='in_progress'&&<button disabled={busy} onClick={()=>change('completed')}>Mark completed</button>}</div>}{!merchant&&<div className="request-controls customer-controls">{request.status==='quoted'&&<button disabled={busy} onClick={()=>change('accepted')}><CheckCircle2 size={16}/> Accept quote</button>}{['pending_quote','quoted'].includes(request.status)&&<button className="danger-soft" disabled={busy} onClick={()=>change('cancelled')}>Cancel request</button>}{request.status==='completed'&&<Link className="request-pay-link" to="/payments">Review payment / escrow</Link>}</div>}{msg&&<div className="final-note">{msg}</div>}</section><section className="final-panel request-chat"><div className="final-panel-head"><h2><MessageCircle size={17}/> Messages</h2></div><div className="request-messages">{messages.length?messages.map(m=><div className={m.sender_id===user.id?'request-message mine':'request-message'} key={m.id}><b>{m.sender_name||'Bizora user'}</b><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString()}</small></div>):<p className="final-empty">No messages yet. Keep service details and agreements here.</p>}</div><form onSubmit={send} className="request-send"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type a message…" maxLength={1500}/><button disabled={busy||!text.trim()}><Send size={17}/></button></form></section></div></main>
}
